### ISSUE TITLE
IDEA: F0 web browser

### ISSUE THREAD

**Issue by mindstormpro3** [EstebanFuentealba/MALVEKE-Flipper-Zero#10]
dear Esteban,

I have an idea to make an app that uses the wifi dev board to connect to wifi and a server to surf the FLIP-net (a server that stores a bunch of FLIP-sites made especialy for the flipper zero) and open/use FLIP-sites to: play games, read, and even check/send E-mails to other flipper zeros. I also hope to allow people to contribute their sites and ideas for development. if you have any questions or concerns about this concept, please respond to this post.

cheers,
Elio Anon

P.S. your Gameboy tools are SOOO COOl!

**Comment by EstebanFuentealba** [comment]
I think it's a great idea as a project, but it might be too extensive and could work better as an independent project.

I believe it would be highly beneficial as long as the functionalities of Flipper Zero can be accessed through the web (IR, SubGhz, NRF, etc.).

Perhaps it could also be maintained as a service in F0 (similar to storage or Bluetooth) so that Wi-Fi communication can be utilized from any application.

For now, I'll close the topic because I think it's a project that doesn't align with MALVEKE's target.

Best regards!

**Comment by mindstormpro3** [comment]
Ok. I’ll do some research
