### ISSUE TITLE
Game Boy Camera doesn't work (probably Card Ridge issue)

### ISSUE THREAD

**Issue by bison--** [EstebanFuentealba/MALVEKE-Flipper-Zero#32]
Hi,

I tested with a Pokemon Yellow Card Ridge that everything works correctly (it seems fine)
![image](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/901400/acdab0f8-2e73-4ddf-981e-80f57f222dcd)

I am not sure if this is how the Gameboy Camera should look like when reading the Card Ridge infos:

![image](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/901400/f49c701e-62b6-47b2-b910-fe37784e9f76)

It might be a "hardware issue" with the cam itself, as in: the camera is pretty lose, the Pokemon Card Ridge sits perfectly.
Both work in the old original grey first gen gameboy.

**Comment by EstebanFuentealba** [comment]
Hi, how are you?

Perhaps you placed the cartridge backwards. Since it doesn't have a casing, the board can be inserted either way, front or back.

Make sure the cartridge pins are aligned like this:

![WhatsApp Image 2024-03-21 at 7 56 29 AM](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/442927/8395c207-94c9-470f-94e3-7e0a4b220e9a)

**Comment by bison--** [comment]
OH WOW! 
You have no idea how stupid I feel now ^^" I actually tried that and was like "nah, feels wrong".

thanks ^^"

**Comment by EstebanFuentealba** [comment]
No, thank you for sharing. I've experienced the same issue, and it's due to a lack of casing to ensure that the cartridges can only be inserted the right way. I'll also add this to the documentation 👍.
